version: '3.3'
services:

  # bungeecord
  bungeecord:
    image: bungeecord
    ports:
      - "25565:25565/tcp"
    networks:
      - main
    depends_on:
      - redis
      - rabbit
      - state

  # lobby
  lobby:
    image: lobby
    environment:
      - SERVERID=lobby
    networks:
      - main

  # redis database
  redis:
    image: redis
    ports:
      - "1000:6379"
    networks:
      - main

  # rabbitmq message broker
  rabbit:
    image: rabbitmq
    networks:
      - main

  # mongo database
  mongo:
    image: mongo
    ports:
      - "27017:27017/tcp"
    networks:
      - main

  # backends
  state:
    image: backend-state
    networks:
      - main

networks:
  main:
    driver: bridge