# This is bungeecord config file. Many of these settings are manipulated by the plugin.

forge_support: false
player_limit: -1

permissions:
  default: []
  admin:
    - bungeecord.command.server
    - bungeecord.command.list
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload

timeout: 30000
log_commands: false
online_mode: true
disabled_commands: []
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:1
    restricted: false

listeners:
  - query_port: 25577
    motd: '&1Natchuz Hub'
    tab_list: SERVER
    query_enabled: false
    proxy_protocol: false
    forced_hosts:
      pvp.md-5.net: pvp
    ping_passthrough: false
    priorities:
      - lobby
    bind_local_address: true
    host: 0.0.0.0:25565
    max_players: 1
    tab_size: 60
    force_default_server: false

ip_forward: true
network_compression_threshold: 256
prevent_proxy_connections: false

groups:
  natchuz:
    - admin

connection_throttle: 4000
stats: ba7e2cee-a7da-43a0-b7a0-7c6a48b3cca3
connection_throttle_limit: 3
log_pings: true
